services:
  database:
    image: mariadb:latest
    container_name: mariaDb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Resume_Analyzer_db
    ports:
      - "3306:3306"
    volumes:
      - database_volume:/var/lib/mysql
    networks:
      - database_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: PhpMyAdmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8099:80"
    depends_on:
      - database
    networks:
      - database_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: KeyCloak
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://database:3306/Resume_Analyzer_db
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_PROXY: "edge"
      KC_FEATURES: "account-api,authorization"
    ports:
      - "8180:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - database
    networks:
      - database_network

volumes:
  database_volume:

networks:
  database_network:
    driver: bridge